from __future__ import annotations

from typing import Final

GCODE_MODAL_GROUP_NON_MODAL: Final[str] = "0"
GCODE_MODAL_GROUP_MOTION: Final[str] = "1"
GCODE_MODAL_GROUP_PLANE_SELECTION: Final[str] = "2"
GCODE_MODAL_GROUP_DISTANCE_MODE: Final[str] = "3"
GCODE_MODAL_GROUP_FEED_RATE_MODE: Final[str] = "5"
GCODE_MODAL_GROUP_UNITS: Final[str] = "6"
GCODE_MODAL_GROUP_CUTTER_RADIUS_COMPENSATION: Final[str] = "7"
GCODE_MODAL_GROUP_TOOL_LENGTH_OFFSET: Final[str] = "8"
GCODE_MODAL_GROUP_RETURN_MODE_IN_CANNED_CYCLES: Final[str] = "10"
GCODE_MODAL_GROUP_COORDINATE_SYSTEM_SELECTION: Final[str] = "12"
GCODE_MODAL_GROUP_PATH_CONTROL_MODE: Final[str] = "13"

__all__ = [
    "GCODE_MODAL_GROUP_NON_MODAL",
    "GCODE_MODAL_GROUP_MOTION",
    "GCODE_MODAL_GROUP_PLANE_SELECTION",
    "GCODE_MODAL_GROUP_DISTANCE_MODE",
    "GCODE_MODAL_GROUP_FEED_RATE_MODE",
    "GCODE_MODAL_GROUP_UNITS",
    "GCODE_MODAL_GROUP_CUTTER_RADIUS_COMPENSATION",
    "GCODE_MODAL_GROUP_TOOL_LENGTH_OFFSET",
    "GCODE_MODAL_GROUP_RETURN_MODE_IN_CANNED_CYCLES",
    "GCODE_MODAL_GROUP_COORDINATE_SYSTEM_SELECTION",
    "GCODE_MODAL_GROUP_PATH_CONTROL_MODE",
]
